---
apiVersion: v1
kind: Service
metadata:
  name: trips-lb
  namespace: api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: trips
  labels:
    app: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryhku7094.azurecr.io/trips-jvr:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SQL_SERVER
              value: "sqlserverhku7094.database.windows.net"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: password
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: OPENAPI_DOCS_URI
              value: "http://localhost"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: username
