---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-lb
  namespace: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tripviewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: tripviewer
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryhku7094.azurecr.io/tripviewer-jvr:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SQL_SERVER
              value: "sqlserverhku7094.database.windows.net"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: password
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: OPENAPI_DOCS_URI
              value: "http://localhost"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: username
            - name: TRIPS_API_ENDPOINT
              value: "http://trips-lb:8080"
            - name: USERPROFILE_API_ENDPOINT
              value: "http://userprofile-lb:8080"
