---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: userprofile-lb
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: userprofile
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-vaulttripinsights-system-msi"
      containers:
        - name: userprofile
          image: registryhku7094.azurecr.io/userprofile-jvr:latest
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SQL_SERVER
              value: "sqlserverhku7094.database.windows.net"
            # - name: SQL_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: sqldbaccess
            #       key: password
            - name: SQL_DBNAME
              value: "mydrivingDB"
            # - name: SQL_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: sqldbaccess
            #       key: username
            - name: CONFIG_FILES_PATH
              value: "/mnt/secrets"
