---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: userprofile-lb
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
namespace: api
kind: Deployment
metadata:
  namespace: api
  name: userprofile
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryhku7094.azurecr.io/userprofile-jvr:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SQL_SERVER
              value: "sqlserverhku7094.database.windows.net"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: password
            - name: SQL_DBNAME
              value: "mydrivingDB"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sqldbaccess
                  key: username
