kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-reader
  namespace: web
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-contributor
  namespace: web
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]
